### PR TITLE
Rishabh sambare team

### PR DESCRIPTION
**Pull request by rishabhsamb**
Forgot to make the image square in the last PR, this one is fixed.

### CODE REVIEW

**Comment by ljdursi** [comment]
Hi Rishabh!  Don't worry about travis failing, I've just cancelled Travis runs - we don't use it any more, instead using cloud flare.

But!  your PR has just taught us something new about cloudflare and PRs - it looks like the cloudflare preview only gets built if it's on a branch of the repo.   Let me check the build locally....

**Comment by ljdursi** [comment]
LGTM! image

**Review by ljdursi — APPROVED** [review]
Looks good!  Squash and merge when you get a chance.

**Comment by rishabhsamb** [comment]
> Looks good! Squash and merge when you get a chance.

I'm not sure if this is for me, but I don't believe I have write access to the repo.

**Comment by ljdursi** [comment]
I’ve invited you to the org; when you accept you should be able to commit

**Pull request merged**
