### PR TITLE
Support twitter cards for blog posts and main page

### PR DESCRIPTION
**Pull request by ljdursi**
Will address issue #64 when complete

### CODE REVIEW

**Comment by ljdursi** [comment]
Works for blog posts (but doesn't have relevant image/summary information yet in the pages) but not yet for main page (no title).

**Comment by ljdursi** [comment]
Hi @CourtneyGosselin - not urgent but could you give this a look when you get a chance?

**Review by CourtneyGosselin — APPROVED** [review]
LGTM both on Twitter and Slack!

**Comment by ljdursi** [comment]
Thanks @CourtneyGosselin!

**Pull request merged**
